<?php
return array(
'figure'=>'量体数据',
'idfigure'=>'ID',
'create_date'=>'创建时间',
'height'=>'身高',
'weight'=>'体重',
'figure_type'=>'量体数据类型',
'lw'=>'领围',
'xw'=>'胸围',
'zyw'=>'中腰围',
'tw'=>'臀围',
'stw'=>'上臀围',
'zjk'=>'总肩宽',
'yxc'=>'右袖长',
'zxc'=>'左袖长',
'qjk'=>'前肩宽',
'hyc'=>'后衣长',
'yw'=>'腰围',
'hd'=>'横裆',
'td'=>'通裆',
'hyg'=>'后腰高',
'qyg'=>'前腰高',
'kk'=>'裤口',
'figure_type_0'=>'系统',
'figure_type_1'=>'用户',
'userid'=>'用户ID',
'unit'=>'单位',

'handler'=>'操作',

'figure_name'=>'量体名称',
'employee_name'=>'所属员工',
'figure_mode'=>'服务方式',
'figure_mode_1'=>'上门',
'figure_mode_2'=>'到店',

'figure_name_empty'=>'量体名称不能为空',


'hyjc'=>'后腰节长',
'qyj'=>'前腰节',
'tgw'=>'腿根围',
'ykc'=>'右裤长',
'zkc'=>'左裤长',
'xiw'=>'膝围',

'user_name_exist'=>'用户不存在或已有量体数据',

'user_name_not_empty'=>'不能为空',
'lw_not_empty'=>'领围不能为空',
'xw_not_empty'=>'胸围不能为空',
'zyw_not_empty'=>'中腰围不能为空',
'tw_not_empty'=>'臀围不能为空',
'stw_not_empty'=>'上臀围不能为空',
'zjk_not_empty'=>'总肩宽不能为空',
'yxc_not_empty'=>'右袖长不能为空',
'zxc_not_empty'=>'左袖长不能为空',
'qjk_not_empty'=>'前肩宽不能为空',
'hyc_not_empty'=>'后衣长不能为空',
'yw_not_empty'=>'腰围不能为空',
'td_not_empty'=>'通档不能为空',
'hyg_not_empty'=>'后腰高不能为空',
'qyg_not_empty'=>'前腰高不能为空',
'kk_not_empty'=>'库口不能为空',


);