<?php

return array(
    'admin' => '管理员管理',
    'manage' => '管理',
    'add' => '添加',
    'user_name' => '用户名',
    'real_name' => '真实姓名',
    'nick_name' => '昵称',
    'gender'    => '性别',
    'unknown'   => '保密',
    'male'      => '男',
    'female'    => '女',
    'portrait'  => '头像',
    'edit_ok'   => '管理员信息补充成功',
    'note_password'=>'留空表示不修改密码' ,
    'note_portrait' => '支持格式gif,jpg,jpeg,png',
    'reg_time' => '注册时间',
    'last_login' => '上次登录',
    'logins' => '登录次数',
    'handler' => '操作',
    'email' => '电子邮件',
    'drop_admin' => '删除管理',
    'drop_confirm' => '你确定要删除它吗？该操作不会删除ucenter及其他整合应用中的用户',
    'edit' => '编辑权限',
    'sub'  => '信息维护',
    'system_admin_drop' => '该帐号为系统管理员,不得删除',
    'choose_admin' => '请选择管理员',
    'drop_ok' => '删除成功。',
    'drop_failed' => '删除失败',
    'system_admin_edit' => '该帐号为系统管理员,不得编辑',
    'system_admin_add' => '该帐号为系统管理员,不用添加',
    'mall_setting' => '网站设置',
	'back_setting'=>'后台设置',
    'default'   => '后台登录',
    'setting' => '网站设置',
    'region' => '地区设置',
    'payment' => '支付方式',
	'sitestyle'=>'网站风格',
    'operation' => '操作日志',
	'operationv2' => '操作日志v2',
	'sysmessage'=>'系统通知',
	'messageicategory'=>'消息模版分类',
	'messagetemplate'=>'消息模版',
    'theme' => '主题设置',
    'template' => '首页维护',
    'mailtemplate' =>'通知模板',
    'goods_admin'=>'面料工艺',
    'partfabric'=>'面料管理',
	'createcash'=>'创业者提现审核',
    'liangticash'=>'量体师提现申请',
	
	'profit' =>'创业者收益列表',
	
	


    //ns add
    'partlining'=> '里料采购申请',
    'partmat'=>'工艺搭配',
    'parttype'=>'属性设置',
    'goods_manage'=>'供应商产品',

    //ns add 模块管理
    'module' => '模块管理',
    'satnav' => '主导航管理',
    'shuffling' => '轮播图管理', 
    'motif' => '栏目管理',
    //ns add 产品管理
	'bgoods'=>'产品管理',
    'goods' => '产品列表',
    'gcategory' => '产品分类', 
    'goods_type' => '产品类型',
    'goodsspec' => '产品规格',
    'goodsattribute' => '产品属性',
    'products' => '编辑货品',
    //ns add 定制商品
    'fabric_manage' => '定制商品',
    'fabric_brand' => '属性管理',
    'diyM' => '分类管理',
    'dictC' => '互斥管理',
    'basematerial' => '基料管理',
    'standardpackage' => '规格包装价格管理',
    'effectage'=>'功效犬期价格管理',
    'material'=>'物料规格管理',
    //ns add 会员管理
    'member' => '会员管理',
    'user_manage' => '会员管理',
    'lv' => '会员等级管理',
    'authcyz' => '创业者认证审核',
    'cash' => '创业者提现审核',
    'profit'=>'创业者收益列表',
    'paylist' => '创业者收支列表',
    'pettype'=>'宠物种类管理',
    //ns add 内容发布
    'website' => '内容发布',
    'article_list' => '文章列表',
    'acategory' => '文章分类',
    'elephotos' => '电子相册',
    'active' => '活动发布',
    'folly' => '广告发布',
    'designer' => '创业故事',
    //ns add 信息管理
    'contentsite' => '信息管理',
    'detail_comments' => '商品购买评论',
    'figure_comments' => '量体服务评论',
    'question' => '用户咨询',
    'feedback' => '意见反馈',
    'smsRegTmp' => '短信码记录',
    'dosysmsg' => '系统消息推送',
    'informations' => '重要资讯推送',
    //ns add 营销活动
    'yingxiao' => "营销活动",
    'setting_m' => '麦券管理-设置',
    'setting_f' => '麦券管理-发放记录',
    'setting_voucher' => '优惠券列表',
    'setting_voucher_create' => '优惠券生成',
    'setting_voucher_batch' => '优惠券批次',
    
    'discount' => '商品促销',
    //ns add 订单管理
    'trade'=>'订单管理',
    'order' => '订单列表',
    'delivery' => '发货单列表',
    //ns add 业务管理
    'zctg' => '业务管理',
    'zzm' => '业务组管理',
    'generalize_member' => 'BD信息管理',
    'jx' => 'BD绑定明细',
    'bd_business' => 'BD业绩及提成',
    //ns add 财务管理
    'finance_manage' => '财务管理',
    'client_finance' => '客户明细权限',
    'client_examine' => '账户调解审核',


	'customs'=>'基本款管理',
	'custom_fab'=>'单品选择面料权限',
    'custom'=>'单品管理',
    'fab' => '面料选择上传',
    'swfupload'=>'图片上传',
    'suittype' => '类别搜索',
    //ns add 产品样衣
    'suit' => '套装管理',
	'dissertation'=>'主题系列',
    'gcategory' => '产品分类',
    'customtype' => '产品属性',
    'cfabric' => 'DIY面料管理',
    'dfabric' => '样衣面料',
    'dswitch' => 'DIY开关',
	'fabricbook'=>'面料册管理',
    'linkSuit'=>'关联套装',
    'customattribute' => '属性列表',
    'jpjz_discat' => '主题分类管理',

    'brand' => '供应商品牌管理',
    'market' => '批发市场管理',
    'goods' => '商品管理',
    'recommend' => '推荐类型',
    'consulting' => '咨询管理',
    'store_admin' => '网站管理',
    'sgrade' => '网站等级',
    'scategory' => '网站分类',
    'store' => '网站管理',
    
    'user' => '会员管理',
	'appset'=> 'app版本控制',
	'lt_business'=> '量体师费用统计',

	'user_add'=>'会员添加',
	'user_edit'=>'会员编辑',
//    'single_comments' => '会员晒单评论管理',
//    'order_comments' => '会员订单评论管理',
    'followed_beat' => '会员拍照下单',
    'authperson' => '创业者认证管理',
    'authbusiness' => '企业认证管理',

    //ns add 会员
    'user_manage' => '会员管理',
	'user_add'=>'会员添加',
	'user_edit'=>'会员编辑',
    
	'lv_manage'=>'会员等级管理',
	'lv_add'=>'会员等级添加',
	'lv_edit'=>'会员等级修改',
	'authcyz_edit'=>'审核认证',
    'demand_items' => '需求发布选项',
    'demand'=> '消费者需求列表',
    'followedbeat' => '会员拍照下单',
    'authperson' => '创业者认证管理',
    'authbusiness' => '企业认证管理',
    
	'cash_check'=>'审核提现',
    'dosysmsg' => '系统消息推送',
	'dosysmsg_add'=>'发送系统消息',
    'account_log'=> '账户管理',


		// shao统计报表
		'num_stat'=> '统计报表',
		'numerical_stat'=> '购买清单及复购',
    //ns add 门店管理
    'partners'=>'门店管理',
    'serve' => '门店管理(量体师管理)',
    'figure' => '门店量体数据',
	'shopowner'=>'店长管理',
    'quantity' => '量体师管理',
    'authfigure' => '量体师实名认证',
    'figurecash' => '量体师提现申请',
    'quantity_permissions' => '量体师编辑权限',
    'serve_permissions' => '门店管理编辑权限',


    //ns add 内容发布
	'info_rmation' => '重要资讯推送',
    'article_gl' => '文章列表',
    'trends' => '流行趋势列表',
    'trendscategory' => '流行趋势分类',
    'fashion'=>'潮流发布',
    'partner'=>'友情链接',
    
	'activeindex'=>'活动发布管理页',
	'addactive'=>'添加活动',
	'addlocation'=>'添加位置',
    'shuffling' => '轮播图管理',
	'follyindex'=>'广告发布管理页',
	'follyadd'=>'添加广告',
	'follyaddtpl'=>'添加页面',
	'follyaddlocation'=>'添加广告位',
    'style_recommend' => '产品推荐',
	'jpjz_dissertation' => "产品系列",
	'jpjz_dissertationindex'=>'主题管理',
	'jpjz_dissertationadd'=>'添加主题',
	'jpjz_dissertation_edit'=>'编辑主题',
	'jpjz_dissertation_drop'=>'删除主题',
	'jpjz_discat'=>'主题分类管理',
  'link_suitlist'=>'推荐搭配',
  'sizeTable' => '尺码数据',
  'sizeStyle' => '尺码名称',
	'yh_template' => "衬衫印花",
	'yh_templateindex'=>'印花管理',
	'yh_templatecustom'=>'用户上传印花',
	'yh_templateadd'=>'添加印花模版',
	'yh_categoryindex'=>'印花分类',
	'yh_categoryadd'=>'添加印花分类',
	'shirt'=>'所有衬衫',
	'shirtadd'=>'添加衬衫',
	'designerManage'=>'设计师管理',
	'designerAdd'=>'设计师维护',
    //ns add 信息管理
    'yxgl' => '信息管理',
    'detail_comments' => '订单评论',
    'com_comments'    => '印花|主题评论',
    'figure_comments'    => '量体服务评论',
    'question'=> '会员咨询管理',
    'feedback' => '意见反馈',
    'complaint' => '举报管理',
    'smsRegTmp' => '验证码管理',

    //ns add 营销管理
    'ask' => '线下需求收集',
	'askv2' =>'线下需求收集v2',
    'cy' => '创业者注册申请',
    'favorable_register' => "新会员营销",
    'favorable_frist' => "初次定制营销",
    'favorable_bonus' => "优惠券管理",
    'special_code' => "特权码管理",
	'kuka' => "酷卡管理",
	'favorable_onegift'=>'买一赠一',
    'profit_setting'=>'抵用卷管理',
    'bonus'=>'红包管理',
    'debit'=>'酷卷管理',
    'debit_line' => '酷劵线下',
    'coinconfig' => '购币升级',

    //ns add 看图下单
    'ktxd' => '看图下单',
    'user_upload_img' => "看图下单",

    'user_work_img' => '我的作品',
    'jpjzpart'=>'DIY面料详情',
    'process' => '知识库-工艺',
	'processindex'=>'管理',
	'processadd'=>'新增',
	'pcategoryindex'=>'工艺分类',

	//ns add 即时聊天
    'imchat' => '即时聊天',
    'imchat_manage' => "聊天记录",

    //ns add 众创推广
    'zz_manager' => '组织管理',
    'tgy_manager' => 'BD信息管理',
    'jx_manager' => 'BD业绩管理',


    'comments' => '评论管理',
    'user_upload' => '街拍设计管理',
    'album_admin' => '街拍设计推荐',
    'member_lv' => '会员等级',
    'admin_manage' => '管理员管理',
    'notice' => '会员通知',
	'pcategory' => '工艺分类',
	//'process' => '工艺细节图',
    'groupbuy' => '团购管理',
    'cycleimg' => '轮播图片',
    'navigation' => '页面导航',
    'db' => '数据库',
    'external' => '扩展管理',
    'plugin' => '插件管理',
    'module' => '模块管理',
    'widget' => '挂件管理',
	'sitecity'=>'站点管理',
	'testsite'=>'体验店管理',
    'clear_cache' => '清空缓存',
    'im' => '即时通讯',
    'add_member' => '此会员不存在',
    'to_add_member' => '点击此处添加会员',
    'add_admin_ok' => '添加管理员成功。',
    'add_priv' => '请您分配权限',
    'edit_admin_ok' =>'管理员编辑成功。',
    'already_admin' =>'该帐号已经是管理员',
    'service'  => '是否为客服',
    'yes'      => '是',
    'no'       => '否',
    'admin_list' => '返回管理员列表',
    'user_list' => '返回会员列表',
    'priv' => '权限管理',
    'im_qq' => 'QQ',
    'im_msn' => 'MSN',
    'system_manager' => '系统管理员',
    'input_user_name' => '首先输入您要添加的管理员会员名',
	//'dissertation'    => "专题管理",
	'shipping'    => "配送方式",
    //ns up 修改名称
	'store_manage'    => "设计师管理",
	'store'    => "设计师列表",
    'sgrade' => "模板管理",
    'store_fabric' => "设计师采购申请",
    'store_dispatching'=>"设计师派工量体申请",


     /*订单管理*/
	'bookrefund'=>'换货申请',
	'fx'=>"返修订单",
	'order_manage' => "订单列表",
	'order_editaddress'=>'订单地址修改',
	'order_updateprice'=>'修改订单价格',
	'order_updateorder'=>'修改订单状态',
	'order_manualworking'=>'手动推送订单',
	'order_manualexpress'=>'手动物流单号',
    'fabric_order'=> "料册申请",
    'orderrefund'=>"退款申请",
    'craft' => "订单工艺可选项",
    'jpjz_order' => "即拍即做订单",

    /*即拍即做*/
    'jpjz' => "即拍即做",


    'view'=> "样衣管理",

	'cooluser_lx'    => "流行趋势",
	'cooluser_la'    => "流行趋势分类",
	'favorable_presenter'    => "赠送干洗营销",
	'order_word'    => "单据管理",
	'complaint'    => "举报管理",

	/* zxr添加网站设置子功能 */
	'systemsetting'=>'系统设置',
	'baseinfo'=>'基本信息',
	'emailset'=>'email',
	'captchaset'=>'验证码',
	'storeset'=>'开店设置',
	'creditset'=>'信用评价',
	'subdomain'=>'二级域名',
	'creditscore'=>'订单交易额设定',
	

	/* zxr添加财务管理 */
	'finance_manage'=>'财务管理',
	'client_finance_detail'=>'客户明细账',
	'client_finance_table'=>'客户明细表',
	'estp_finance_detail'=>'创业者收益明细',
  'client_examine' => '账户调解审核',

	/* zxr添加面料管理 */
	'fabric_manage'=>'定制管理',
	'fabric_brand'=>'面料品牌操作权限',
	'fabric_info'=>'面料信息操作权限',
// 	'fabric_brand_manage'=>'面料品牌管理',
// 	'fabric_info_list'=>'面料信息管理',

//  	'fabric_brand_add'=>'面料品牌添加',
//  	'fabric_brand_eidt'=>'面料分类编辑',
// 	'fabric_info_add'=>'添加面料',
// 	'fabric_info_edit'=>'编辑面料',
// 	'fabric_info_location'=>'面料置顶',

//*******add by 小五 面料diy 工艺部分***************//
	'diy_manage'=>'DIY配置管理',
	'dict_manage'=>'工艺组件管理',
	'dict_crossrule'=>'工艺冲突管理',
);

?>
