<?php
return array(
    'gcategory' => '商品分类',
    'alias' => '分类别名',
    'cate_name_empty'=>'请选择产地',
    'number_only'=>'分类排序仅能为数字',
    'cate_name' => '分类名称',
    'parent_id' => '上级分类',
    'add_child' => '新增下级',
    'add_ok' => '新增分类成功。',
    'back_list' => '返回分类列表',
    'continue_add' => '继续新增分类',
    'name_exist' => '该分类名称已经存在了，请您换一个',
    'gcategory_empty' => '该分类不存在，请您返回后刷新页面',
    'edit_brand_ok' => '编辑数据成功。',
    'edit_again' => '重新编辑该分类',
    'no_gcategory_to_drop' => '请您选择要删除的分类',
    'drop_ok' => '删除分类成功。',
    'drop_confirm' => '删除该分类将会同时删除该分类的所有下级分类，您确定要删除吗',
    'order_empty'  => '排序不能为空',
    'add_if_show'      => '新增的分类名称是否显示',
    'update_order' => '更新排序',
    'update_order_ok' => '更新排序成功。',
    'no_change' => '保持不变',
    'batch_edit_ok' => '批量编辑成功。',
    'file_format_desc' =>
        '<table border="1">'.
        '<tr><td>一级分类</td></tr>'.
        '<tr><td></td><td>二级分类</td></tr>'.
        '<tr><td></td><td>二级分类</td></tr>'.
        '<tr><td></td><td></td><td>三级分类</td></tr>'.
        '<tr><td>一级分类</td></tr>'.
        '</table>',
    'no_data'  => '暂无商品分类',
    'editable' => '可编辑',
    'max_layer_error' => '请确保商品分类不超过四级',
    'intro_tip'    => '推荐到频道页',
    'intro'   => "推荐",
    'layer'   => "层级",
    'layer_tip' => "当前分类下商品在试衣间整体效果中所在的图层位置",
    'theme'  => '模板',
    'theme_tip' => "选择显示该分类的模板",
    'layer_empty' => '层级不能为空',
    'layer_number_only' => "层级只能为数字",
    'link_attr' =>  "关联商品属性",
    'link_attr_tip' => "关联属性可在前分类页面筛选商品",
    'select_type'   => "请选择类型",
    'select_attr'   => "请选择属性",
    'exist_attr'    => "属性已存在",
    'keywords'      => "SEO 关键字",
    'keywords_tip'  => "页面头部关键字",
    "description"   => "SEO 描述",
    "description_tip" => "页面头部描述信息",
    'link_goods'    => "推荐搭配商品",
    'pls_select_goods' => "-=请选择商品=-",
    'goods_name' => "商品名称",
    'search'  => "搜索",
    'nogoods' => "未匹配到商品",
    'alert_catandgoods' => "请选择分类或者填写商品名称",
    'add' => "添加属性",
    'goods_exist' => "商品已存在",
	'region_name'=>"*属性名称",
	'region_alert'=>"注：不可重复添加属性名称",
	'select_pls' => "请选择所属分类",
    'if_def' => "设为默认选项",
    'manage' => "属性管理",
    'bset' => "基本设置",
);
?>