<?php

return array(
        'ORDER_STATUS' => array(
                // ORDER_PENDING    => '待付款', // 11
                // STORE_ACCEPTED   => '裁缝已付款', // 19   如果裁缝下单时选择消费者 货到付款 跳过消费者付款 下一个状态为 审核中 //暂时放弃货到付款
                // ORDER_ACCEPTED   => '消费者已付款', // 20   过度状态，不会停留显示
                // ORDER_CHECKING   => '审核中', // 13
                // ORDER_CHECKFAIL  => '审核失败', // 14
                // ORDER_CHECKED    => '审核成功', // 15    过度状态，不会停留显示
                // ORDER_PRODUCTION => '生产中', // 60
                // ORDER_SHIPPED    => '平台已发货', // 30
                // STORE_RECEIVED   => '裁缝已收货', // 31
                // STORE_SHIPPED    => '裁缝已发货', // 32
                // ORDER_FINISHED   => '交易成功', // 40   （成功订单可评价一次）
                // ORDER_CANCELED   => '已作废', // 0
                //ns add 订单状态   // -- sin modi 2015-05-14 09:15:47
                ORDER_PENDING => '待付款', //11 待付款
//                 ORDER_WAITFIGURE => '待量体', //12 待量体
                ORDER_ACCEPTED => '已支付', //20 已支付
                //ORDER_CHECKING => '订单审核', //13
//                 ORDER_PRODUCTION => '生产中', //60 //生产中
                ORDER_STOCKING => '待发货',   // 61
                ORDER_SHIPPED => '已发货', //30
//                 ORDER_REPAIR => '返修中', //41
                ORDER_FINISHED => '已完成', //40
                ORDER_CANCELED => '已作废', //0
//                 ORDER_ABNORMAL => '生产中', //43 订单异常(订单推送异常)
//                 ORDER_SHIPERROR => '生产中', //44 订单异常(物流推送异常)
        ),
        'ORDER_PENDING' => ORDER_PENDING, //待付款
        'ORDER_SHIPPED' => ORDER_SHIPPED, //已发货
        'ORDER_FINISHED' => ORDER_FINISHED, //已完成
        'ORDER_STOCKING' => ORDER_STOCKING, //备货中

        'emb_site' => '位置',
        'emb_font' => '字体',
        'emb_color' => '颜色',
        'emb_con' => '内容',
    'sc'  =>  '简体',
    'tc'  =>  '繁体',
    //ns add 酷客基地
    'kuke'=>'酷客中心',
    'trading' => '交易管理',
    'service_manage' => '服务管理',
    'fabric_manage' => '面料管理',
    'fabric_query' => '面料查询',
    'my_sincerity'=>'我的诚信度',
    'sincerity'  =>'诚信度',
    'service_desc' => '服务说明',
    'home_manage' => '主页管理',
    'service_info' => '服务信息',
    'my_rc' => '我的账户',
    'my_buyer_order'=> '我的订单',
    'safety'=> '安全设置',
    'username'  =>  '用户名',
    'password'  =>  '密&nbsp;&nbsp;&nbsp;码',
    'captcha'   =>  '验证码',
    'index'     =>  '首页',
    'my_userInfo'     => '个人中心',
    'overview'      => '账户概览',
    'member_center' => '用户中心',
    'hello'         => '您好',
    'login'         => '登录',
    'register'         => '注册',
    'search' => '搜索',
    'shopping_cart'         => '购物车',
    'favorite'         => '收藏夹',
    'favorite_sunsingle'         => '收藏的晒单',
    'favorite_demand'         => '收藏的作品',
    'favorite_works'         => '收藏的需求',
    'favorite_custom'         => '收藏的成衣',
    'favorite_fabric'         => '收藏的面料',
    'pm'         => '站内消息',
    'user_center' => '用户中心',
    'relation' => '关系管理',
    'help_center'         => '帮助中心',
    'i_want_buy'         => '我要买',
    'i_want_sell'         => '我要卖',
    'im_buyer' => '我是会员',
    'im_seller' => '我是供应商',
    'curlocal'         => '当前位置',
    'search_goods'         => '搜索商品',
    'search_store'         => '搜索店铺',
    'search_groupbuy'      => '搜索团购',
    'my_profile'    => '我的个人中心',
	'no_data'=>'暂无数据',
    'my_credit'                  => '我的信用',
    'my_address'                  => '收货地址',
    'my_body'                     =>'量体数据',
    'my_vip'                     =>'会员政策',
    'my_order'                  => '我的订单',
    'my_demand'                  => '我的需求',
    'my_works'                  => '我的案例',
    'my_buyer'                  => '我的消费者',
    'my_cart'                  => '我的购物车',
    'my_sunsingle'                  => '我的晒单',
    'my_question'             => '我的咨询',
    'my_goods'                  => '商品管理',
    'my_password'                  => '修改密码',
    'my_follow'              => '我的关注',
    'complaint'              => '投诉管理',
    'my_complaint'              => '我发起的投诉',
    'my_qa'              => '咨询管理',
    'my_qa_list'        => '咨询列表',
    'my_favorite'      => '个人收藏',
    'apply_store'      => '申请开店',
    'my_category'      => '分类管理',
    'order_manage'      => '订单管理',
    'my_store'      => '店铺设置',
    'my_theme' => '主题设置',
    'my_payment'      => '支付方式管理',
    'my_shipping'      => '配送方式管理',
    'my_navigation'      => '导航管理',
    'my_partner'      => '合作伙伴管理',
    'my_coupon'       => '我的优惠券',
    'logout'                    => '退出',
    'guest'         => '游客',
    'consignee'      => '收货人姓名',
    'region'      => '所在地区',
    'address'      => '详细地址',
    'zipcode'      => '邮政编码',
    'phone'      => '电话/手机',
    'phone_tel'      => '电话号码',
    'phone_mob'      => '手机号码',
    'handle'      => '操作',
    'add' => '新增',
    'edit'      => '编辑',
    'submit'    => '提交',
    'reset'     => '重置',
    'goback'    => '返回',
    'drop_confirm'  => '您确定要删除它吗？',
    'title'  => '标题',
    'link'  => '链接',
    'logo'  => '标识',
    'sort_order'  => '排序',
    'drop'  => '删除',
    'checkall'  => '全选',
    'bottom'    => '底部',
    'header'    => '顶部',
    'middle'    => '中部',
    'yes'       => '是',
    'no'        => '否',
    'collect_goods' => '收藏商品',
    'collect_store' => '收藏店铺',
	'collect_customs' => '收藏基本款',
    'thumb'     => '缩略图',
    'goods_name'=> '商品名称',
    'store_name'=> '店铺名称',
    'price'     => '价格',
    'add_time'  => '添加时间',
    'stock'     => '库存',
    'brand'     => '品牌',
    'input_keywords'    => '输入关键词',
    'user_name' => '用户名',
    'sgrade'     => '等级',
    'add_to_cart'=> '放入购物车',
    'select_pls' => '请选择...',
    'enabled'   => '启用',
    'go_back'       => '返回上一页',
    'auto_redirect' => '如果您不做出选择，系统将自动跳转',
    'config'        => '配置',
    'install'       => '安装',
    'uninstall'     => '卸载',
    'uninstall_confirm' => '您确定要卸载它吗？',
    'no_records'    => '没有符合条件的记录',
    'no_such_order' => '没有指定的订单',
    'payment_disabled_by_system'    => '支付方式被禁用',
    'payment_disabled'          => '指定的支付方式没有被启用',
    'forbidden'     => '禁止访问',
    'no_such_payment'   => '没有指定支付方式',
    'has_error'     => '在处理您的请求时出现了问题:<br />',
    'check_match_error' => '检查合法性出错',
    'no_valid_data'     => '无有效的数据',
    'order_sn'      => '订单号',
    'order_amount'  => '订单总价',
    'order_status'  => '订单状态',
    'cancel_order'  => '取消订单',
    'pay'           => '付款',
    'view_order'    => '查看订单',
    'discount'      => '折扣',
    'shipping_fee'  => '配送费用',
    'store_index' => '店铺首页',
    'credit_evaluation' => '信用评价',
    'goods_detail' => '商品详情',
    'collect_the_store' => '收藏该店铺',
    'send_pm' => '发站内信',
    'credit_value' => '信用度',
    'goods_count' => '商品数量',
    'store_add_time' => '创店时间',
    'certification' => '认证',
    'enter_store' => '逛逛店主的店铺',
    'search_in_store' => '店内搜索',
    'gcategory' => '商品分类',
    'scategory' => '店铺分类',
    'goods_history' => '浏览历史',
    'shopwindow_recommended' => '橱窗推荐',
    'all_goods' => '全部商品',
    'kind_of_goods' => '种商品',
    'cert_autonym' => '实名认证',
    'cert_material' => '实体店铺',
    'all_categories' => '全部分类',
    'not_allowed_type' => '您上传的文件格式不正确',
    'not_allowed_size' => '您上传的文件大小超过了允许值',
    'dir_doesnt_exists' => '上传文件存放目录无法创建，请联系站长检查相应权限',
    'no_ftp_server' => '未指定ftp服务器，请联系站长解决此问题',
    'captcha_failed' => '验证码输入错误',
    'login_error' => array(
        '-1' => '您输入的用户名或密码不正确，请重新输入',
        '-2' => '您的账户无法使用，可能是因为用户名重复或不符合规则',
    ),
    'login_successed'   => '登录成功。',
    'logout_successed'  => '退出登录成功。',
    'not_storeadmin'    => '您还没有申请裁缝，无权访问页面。',
    'apply_now' => '立即申请裁缝',
    'no_permission'     => '您没有被授予相应的权限，无权访问',
    'apply_not_agree'   => '您的店铺尚未开通，我们会尽快处理您的申请。',
    'store_is_closed'   => '您的店铺已被关闭，请联系网站管理员开通。',
    'the_store_is_closed' => '该店铺已被关闭，请稍后再访问。',
    'has_login'         => '您已经登录了',
	'no_phone'         => '您还未绑定手机号',
	'no_login'         => '您还未登录,',
    'cart'              => '购物车',
    'store_goods'       => '店铺商品',
    'quantity'          => '数量',
    'subtotal'          => '小计',
    'store'          => '店铺',
    'shopping_step_one'          => '选购商品',
    'shopping_step_two'          => '完成订单信息并下单',
    'shopping_step_three'          => '下单完成并支付',
    'goods_amount'          => '商品总价',
    'no_such_goods'          => '没有指定的商品',
    'no_such_spec'          => '没有指定的规格',
    'goods_unit'          => '件',
    'shipping_fee'          => '配送费用',
    'order_amount'          => '订单总价',
    'no_such_order'          => '没有指定的订单',
    'store_no_payment'          => '指定的店铺没有该支付方式',
    'no_such_payment'          => '没有指定的支付方式',
    'forbidden'          => '禁止访问',
    'required_field'    => '有必填项未填',
    'autov_length_lt_min'   => '字符串长度不足',
    'autov_length_gt_max'   => '字符串长度超出限制',
    'not_allowed_type' => '您上传的文件格式不正确',
    'not_allowed_size' => '您上传的文件大小超过了允许值',
    'cashier'          => '收银台',
    'create_order'     => '生成订单',
    'mall_index'       => '网站首页',
    'order_pending'     => '待付款',
    'order_accepted'   => '待发货',
    'order_canceled'    => '已取消',
    'order_submitted'   => '已提交',
    'order_shipped'     => '已发货',
    'order_finished'    => '已完成',
    'prev_page' => '上一页',
    'next_page' => '下一页',
    'first_page' => '首页',
    'last_page' => '末页',
    'turn_page' => '翻页',
    'total_item' => '共 %s 个项目',
    'invoice_no'    => '物流单号',
    'operate_reason' => '操作原因',
    'cancel_confirm' => '您确定要取消吗?',
    'cancel_reason' => '取消原因',
    'pending_orders'    => '待付款的',
    'submitted_orders'    => '已提交的',
    'accepted_orders'    => '待发货的',
    'shipped_orders'    => '已发货的',
    'finished_orders'    => '已完成的',
    'canceled_orders'    => '已取消的',
    'message' => '我的消息',
    'serve_message' => '服务通知',
    'i_notification' => '互动通知',
    'i_remind' => '互动提醒',
    't_reminding' => '交易提醒',
	'c_reminding' => '投诉提醒',
    'comment' => '评论',

    'confirm'   => '确认',
    'cancel'   => '取消',
    'notice'    => '注意',
    'buyer_name'    => '会员',
    'export' => '导出',
    'import' => '导入',
    'note_for_export' => '您店铺的数据是以 utf-8 编码存储的，导出时是否需要把数据转换为 %s 编码？',
    'reason_for_convert' => '如果您导出的文件需要用 excel 打开，请选择“是”，否则打开时可能显示乱码；如果您导出的文件只是为导入使用，建议不要转换，这样可以节省转换编码的时间。',
    'select_file' => '请选择文件',
    'select_charset' => '请选择文件编码',
    'note_for_import' => '如果文件较大，建议您先把文件转换为 %s 编码，这样可以避免转换编码时耗费时间',
    'note_for_file' => '如果导入速度较慢，建议您把文件拆分为几个小文件，然后分别导入',
    'import_ok' => '导入数据成功。',
    'file_format' => '文件格式',
    'file_format_limit' => 'csv文件',
    'friend' => '我的关注',
    'fans' => '我的粉丝',
    'payment_name'  => '支付方式',
    'email' => '电子邮件',
    'shipping_name' => '配送方式',
    'invoice_no'    => '物流单号',
    'pay_time'      => '支付时间',
    'ship_time'     => '发货时间',
    'finished_time' => '完成时间',
    'order_info'    => '订单信息',
    'consignee_info'=> '收货人及物流信息',
    'goods_info'    => '商品信息',
    'evaluation_good'   => '好评',
    'evaluation_acceptable' => '中评',
    'evaluation_bad'    => '差评',
    'order_eval' => array(
        '1' => '差评',
        '2' => '中评',
        '3' => '好评',
    ),
    'sex' => array(
        '1' => '差评',
        '2' => '中评',
        '3' => '好评',
    ),

    'use'           => '使用',
    'preview'       => '预览',
    'query_info' => '页面执行 %0.3f 秒， 查询 %d 次，在线 %d 人',
    'gzip_disabled' => '，Gzip 已禁用',
    'gzip_enabled' => '，Gzip 已启用',
    'memory_info' => '，占用内存 %0.2f MB',
    'back_list'     => '返回列表',
    'cancel_search' => '取消搜索',
    'cancel_search_notice' => '查看所有结果',
    'field_required'    => '此项必填',
    'at'        => '在',
    'reason'    => '原因',
    'back_index' => '返回首页',
    'cancel_query' => '取消检索',
    'pay_message' => '支付消息',
    'default_site_description' => '这是一个网上网站',
    'default_closed_reason' => '网站维护中，暂时关闭，请稍候访问。',
    'rctailor_sysmsg' => '系统信息',
    'page_close'   => '关闭页面',
    'the_store_not_exist' => '该店铺不存在，请核实后再访问',
    'subdomain' => '二级域名',
    'function_limit'    => '附加功能',
    'bat_upload' => '批量上传',
    'uploaded_files' => '已传图片',
    'insert_editor' => '插入编辑器',
    'insert_article' => '插入文章',
    'no_image_droped' => '不存在此文件，请刷新后再试',
    'upload_types' => '图片上传',
    'com_upload' => '普通上传',
    'rem_upload'   => '远程地址',
    'button_text' => '选择本地图片(每张限%s)',
    'upload' => '上传',
    'com_upload_tips' => '请选择本地图片上传',
    'remote_upload_tips' => '请输入远程图片地址',
    'canceled' => '已取消',
    'import_taobao' => '淘宝助理导入',
    'auth_failed'           => '用户名或密码错误',
    'old_auth_failed'       => '旧密码验证失败',
    'user_exists'           => '用户已存在',
    'cannot_add_myself'     => '无法添加自己',
    'invalid_user_name'     => '无效的用户名',
    'blocked_user_name'     => '用户名中包含不允许注册的词语',
    'email_error'     => 'email地址错误',
    'blocked_email'     => '您的email地址不允许注册',
    'email_exists'     => '该email已被注册',
    'no_such_user'     => '没有指定的用户',
    'user_protected'     => '该用户受保护',
    'unknow_error'     => '未知错误',
    'uc_drop_user_failed'     => '从UC中删除用户失败',
    'password_error'     => '密码错误',
    'answer_error'     => '安全提问答案错误',
    'friendly_remind'  => '友情提示：',
    'close' => '关闭',
    'colon' => '：',
    'note_for_upload' => '支持jpg和gif格式的图片，上传单张图片大小不能超过500k.纽扣/面料/里料的图片尺寸应在宽375*高500',
    'uploadedfile' => '上传文件',
    'close_store_notice' => '关闭店铺通知',
    'your_store_is_closed' => '您的店铺已被关闭，原因是：%s',
    'close_reason' => '店铺已到期',
    'not_seller' => '您目前不是供应商，您可以',
    'login_please' => '您需要先登录才可以执行该操作',
    'consigness_info' => '收货人信息',
    'coupon' => '优惠券管理',
	'special_code' => '特权码管理',
    'kuka' => '酷卡管理',
    'involid_data' => '无效的数据',
    'comma' => '，',
    'whitespace' => '　',
    'groupbuy_manage' => '团购管理',
    'group_pending' => '未发布',
    'group_on' => '进行中',
    'group_end' => '已结束',
    'group_finished' => '已完成',
    'group_canceled' => '已取消',
    'group_all' => '全部团购',
    'group_auto_cancel' => '团购活动结束%s天后供应商未确认完成，活动自动取消',
    'cancel_title' => '“%s”团购活动已经取消',
    'end_title' => '您发起的“%s”团购活动已经结束',
    'end_content' => '请尽快到“已结束的团购”完成该团购活动，以便会员可以完成交易，如结束后%s天未确认完成，该活动将被自动取消,查看<a href ="index.php?app=seller_groupbuy&state=end">已结束的团购</a>',
    'my_groupbuy' => '我的团购',
    'lefttime_format_1' => '%i分钟',
    'lefttime_format_2' => '%h小时%i分',
    'lefttime_format_3' => '%d天%h小时',
    'lefttime'  => '剩余',
    'groupbuy_price' => '团购价',
    'nav_groupbuy'  => '团购活动',
    'sku'   => '货号',
    'not_support_function' => '很抱歉，您的店铺等级不支持该附加功能，如需升级店铺等级，请联系管理员。',
    'view_detail' => '，<a target="_blank" href="%s">查看详情</a>',
    'feed_order_created' => array(
        'title'     => '{actor} 在店铺 {store} 购买了商品',
        'body'      => '',
        'name'      => '订单生成',
    ),
    'feed_store_created'    => array(
        'title'     => '{actor} 在 {mall_name} 开通了店铺 {store}',
        'body'      => '',
        'name'      => '店铺开通',
    ),
    'feed_goods_created'    => array(
        'title'     => '{actor} 添加了商品 {goods}',
        'body'      => '',
        'name'      => '添加商品',
    ),
    'feed_groupbuy_created'    => array(
        'title'     => '{actor} 添加了团购 {groupbuy}',
        'body'      => '团购说明：{groupbuy_message}',
        'name'      => '添加团购',
    ),
    'feed_goods_collected'    => array(
        'title'     => '{actor} 收藏了商品 {goods}',
        'body'      => '',
        'name'      => '收藏商品',
    ),
    'feed_store_collected'    => array(
        'title'     => '{actor} 收藏了店铺 {store}',
        'body'      => '',
        'name'      => '收藏店铺',
    ),
    'feed_goods_evaluated'    => array(
        'title'     => '{actor} 给了商品 {goods} {evaluation}',
        'body'      => '评价：{comment}',
        'name'      => '评价商品',
    ),
    'feed_groupbuy_joined'    => array(
        'title'     => '{actor} 参加了团购 {groupbuy}',
        'body'      => '',
        'name'      => '参加团购',
    ),
    'baidu_shoucang' => '百度收藏',
    'qq_shuqian' => 'QQ书签',
    'renrenwang' => '人人网',
    'kaixinwang' => '开心网',
    'tags' => '标签(TAG)',
    'msg_instruction' => '站内消息使用格式?',
	'epay_name'   => '余额支付',
	'money_log'   => '财务明细',
	'zaixianchongzhi'   => '在线充值',
	'zhanghutixian'   => '账户提现',
	'epay_set'   => '账户设置',
	'yuezhuanzhang' => '余额转账',

	'zhanghuzongjinere'    => '账户总金额：',
	'yuan'    => '元',
	'dongjiejine'     => '冻结金额：',
	'chongzhi' => '充值',
	'tixian' => '提现',
	'chongzhitixian'      => '充值提现',

	/*手机短信功能语言*/
	'msg' => '手机信息',
	'cuowu_zhifumimabunengweikong' => '错误：支付密码不能为空！',
	'cuowu_zhifumimayanzhengshibai' => '错误： 支付密码验证失败!',
	'cuowu_zhanghuyuebuzu' => '错误：账户余额不足！',
	'cuowu_duanxingongnengweikaiqi' => '错误：短信功能为开启！',
	'send_msg_successed' => '错误：短信发送成功！',
	'cuowu_duanxinfasongshibai' => '错误：短信发送失败！',
	'cuowu_shoujihaomabunengweikong' => '错误：手机号码不能为空',
	'cuowu_neirongbunengweikong' => '错误：短信内容不能为空',

	/*服务点*/
	'im_service'=>'我是服务点',
	'service'=>'服务点信息',
    'servedetail'=>'服务点主页',
	'brokerage_log'=>'佣金分成记录',
	'figure'=>'量体数据管理',
 	'add_figure'=>'提交量体数据',
	'employee'=>'员工信息管理',
    'my_order_serve'=>'我的消费者',
    'my_order_serve_2'=>'量体收益',

    'subscribeinfo'=>'消费者预约服务',

	'im_partner'=>'我是加盟商',
	'partner'=>'加盟商信息',

    'figureorder'=>'服务点的订单',

	'invoiceneed' => array(
				'0' => "不需要开发票",
				'1' => "索要发票"
			),

    'invoicetype' => array(
    			'1' => "个人",
    			'2' => "公司"
    		),
	'invoicecontent' => array(
				'1' => "服装"
			),
    'goIndex' => array(
            1=> '去主站'
    ),
    'go_app' => array(
        1 => '个人信息',
        2 => '订单信息',
        3 => '个人收藏',
        4 => '量体信息',
        5 => '配送地址',
        6 => '会员政策',
        7 => '我的量体'
    ),
    'footer' =>'Copyright © mfd.麦富迪  All Rights Reseved. 鲁ICP备0000000号',
    'store_arrt_list' => array(
        1 => array(
            1 => array('name'=>'上门量体','ch'=>'smlt'),
            2 => array('name'=>'到店服务','ch'=>'ddfw')
        ),
        2 => array(
            1 => array('name'=>'商务','ch'=>'sw'),
            2 => array('name'=>'婚礼','ch'=>'hl'),
            3 => array('name'=>'休闲','ch'=>'xx'),
            4 => array('name'=>'职场','ch'=>'zc'),
            5 => array('name'=>'时尚','ch'=>'ss'),
            6 => array('name'=>'校园','ch'=>'xy'),
            7 => array('name'=>'欧美','ch'=>'om')
        )
    ),
    //ns add 订单语言包
    'order_cloth' =>array(
        3    => '上衣',
        2000 => '西裤',
        3000 => '衬衣',
        4000 => '马夹',
        6000 => '大衣',
    ),
    'order_status' =>array(
        11=>'未付款',
        20=>'已付款',
        30=>'已发货',
        40=>'成功',
        0=>'已取消',
        50=>'待量体',
        60=>'生产中',
        70=>'退款中',
        80=>'已退款',
    ),

    'Umsg' => array(
        '1' => '%s 已为您下了订单, <a href="%s" target="_blank">查看详情</a>',           //交易提醒
        '2' => '%s 评论了你发表的晒单, <a href="%s" target="_blank">查看详情</a>',        //晒单评论
        '3' => '您的消费者 %s 对你的服务进行了评价, <a href="%s" target="_blank">查看详情</a>', //订单评论
        '4' => '%s 新发布了新的定制需求, <a href="%s" target="_blank">前往查看</a>', //消费者发需求
        '5' => '你关注的 %s 裁缝发布了新作品, <a href="%s" target="_blank">前往查看</a>', //裁缝发作品
        '6' => '%s 裁缝为你提供了 %0.2f元的报价, <a href="%s" target="_blank">查看详情</a>',  //裁缝发报价
        '7' => '尊敬的裁缝您好 %s 消费者已将他的定制服务选择您为中标者, <a href="%s" target="_blank">请点击此处</a>及时关注！',  //裁缝发报价

		'8' =>  '%s 对您的服务行为进行举报，举报内容：%s  ，若举报成立将扣除您的诚信度分值，请等待客服处理结果。',//被举报 接收提示
		'11' => '%s 对您的作品评选进行了评论，评论内容：%s',//作品评选
    )
);

?>
